name: Pre-Build + Capacitor 
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  
  schedule:
    - cron:  '1 22 * * *'

    # * is a special character in YAML so you have to quote this string


jobs:
  # This will build an IPA & Upload the artifact in iOS.zip

  # 
  build-ios-test:
    runs-on: ubuntu-latest
    steps:
      - name: PreBuild Capacitor iOS
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.SECRET }}
          app-id: 3284dc51
          platform: iOS
          build-type: development
          certificate: ios_dev
          native-config: ios_dev
          upload-artifact: ios
          build-stack: macOS - 2021.10
          artifact-retention-days: 1

      - name: Report Status
        if: always()
        uses: likhith99/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
          
    # 
  build-web-test:
    runs-on: ubuntu-latest
    steps:
      - name: Pre Build Capacitor web Test
        uses: ionic-team/appflow-build@v1
        with:
          token: ${{ secrets.SECRET }}
          app-id: 3284dc51
          platform: Web

      - name: Report Status
        if: always()
        uses: likhith99/notify-slack-action@master
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}        

